Repository arquillian/ike-prow-plugins, pull requests merged in 2018-06, with the labels that each got.

#173 fix(#172): uses blob in config link when redirects to github.com
  pkg/github/service/config_loader.go
  pkg/github/service/raw_file_service.go
  pkg/plugin/test-keeper/configuration_gh_test.go
Labels: size/S

#147 feat(#61); add '/run all' or '/run plugin-name' command to trigger respective plugin
  cluster/osio-plugins.yaml
  docs/plugins.adoc
  glide.lock
  pkg/command/cmd_executor.go
  pkg/command/run_command.go
  pkg/plugin/test-keeper/comment_cmd.go
  pkg/plugin/test-keeper/event_handler.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/run_cmd/pr_details.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/run_cmd/trigger_run_all_comment_by_admin.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/run_cmd/trigger_run_test-keeper_comment_by_pr_reviewer.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/run_cmd/trigger_run_work-in-progress_comment_by_pr_reviewer.json
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/plugin/work-in-progress/test_fixtures/github_calls/collaborators_external-user_permission.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/collaborators_repo-admin_permission.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_details.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_details_wip.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/trigger_run_all_on_wip_pr_by_admin.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/trigger_run_test-keeper_on_pr_by_pr_creator.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/trigger_run_work-in-progress_on_pr_by_pr_creator.json
  plugins.yaml
Labels: size/XXL

#176 chore(#175): expose pmcd-implants port(44321) as service
  cluster/hook-template.yaml
  cluster/ike-prow-template.yaml
Labels: size/S

#174 docs(#104): update test keeper images.
  docs/images/test-keeper-failure.png
  docs/images/test-keeper-success.png
Labels: size/XS

#178 chore(#177): expose pmcd service port on 44321 instead of 80
  cluster/hook-template.yaml
  cluster/ike-prow-template.yaml
Labels: size/XS

#179 chore(#181): listening on 8888 for /metrics in prow+pmcd.sh
  prow+pmcd.sh
Labels: size/XS

#171 refactor(#122): make plugin hint effective for all plugins
  pkg/assets/config/message-with-config.txt
  pkg/assets/config/message-with-hint-file-not-found.txt
  pkg/assets/config/message-with-no-config.txt
  pkg/hint/hint_message_loader.go
  pkg/hint/hint_message_loader_test.go
  pkg/hint/hint_suite_test.go
  pkg/plugin/test-keeper/comment_message.go
  pkg/plugin/test-keeper/comment_message_test.go
  pkg/plugin/test-keeper/event_handler.go
  pkg/plugin/test-keeper/hint_message.go
Labels: size/XL

#185 chore(#184): change name to make it consistent with default metrics
  pkg/server/metrics.go
Labels: size/S

#190 chore: use pr loader constuctor instead of helper method
  pkg/plugin/test-keeper/event_handler.go
Labels: size/S

#195 fix(#194): every around function execute also inner(earlier) around function
  pkg/github/client/pagination_checker.go
  pkg/github/client/pagination_checker_test.go
  pkg/github/client/rate_limit_watcher.go
  pkg/github/client/rate_limit_watcher_test.go
  pkg/github/client/retry_wrapper_test.go
Labels: size/M

#187 feat(#186): implement custom metrics for test-keeper
  glide.lock
  pkg/plugin/plugin_init.go
  pkg/plugin/pr-sanitizer/cmd/main.go
  pkg/plugin/test-keeper/cmd/main.go
  pkg/plugin/test-keeper/event_handler.go
  pkg/plugin/test-keeper/metrics.go
  pkg/plugin/test-keeper/metrics_test.go
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/pr_details_for_metrics.json
  pkg/plugin/work-in-progress/cmd/main.go
  pkg/server/metrics.go
  pkg/server/metrics_test.go
  pkg/server/server.go
  pkg/utils/metrics.go
Labels: size/XL

#193 feat(#139): make AnyOf function lazy in evaluating the inner checks
  pkg/command/cmd_executor.go
  pkg/command/cmd_executor_test.go
  pkg/command/permission_funcs.go
  pkg/command/permission_service.go
  pkg/command/permission_service_test.go
  pkg/command/permission_types.go
  pkg/plugin/test-keeper/comment_cmd.go
Labels: size/L

#207 chore(#202): lock prometheus dependency
  glide.lock
  glide.yaml
Labels: size/S

#206 chore: modify cico script to build pr-sanitizer
  cico_setup.sh
Labels: size/XS

#203 feat(#182): adds /run command support for pr-sanitizer.
  glide.lock
  pkg/plugin/pr-sanitizer/event_handler.go
  pkg/plugin/pr-sanitizer/event_handler_gh_test.go
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/pr_details_w_title_type.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/pr_details_wo_title_type.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/trigger_run_all_on_pr_by_admin.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/trigger_run_pr-sanitizer_on_pr_by_pr_creator.json
  pkg/plugin/test-keeper/event_handler.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/metrics_test.go
  pkg/plugin/test-keeper/test_fixtures/github_calls/collaborators_external-user_permission.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/collaborators_repo-admin_permission.json
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/plugin/work-in-progress/test_fixtures/github_calls/collaborators_external-user_permission.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/collaborators_repo-admin_permission.json
  plugins.yaml
Labels: size/XXL

#205 chore(#204): enable pr-sanitizer plugin for ike-prow-plugins
  cluster/osio-plugins.yaml
Labels: size/XS

#208 refactor(#197): event handler interface to abstract common logic.
  glide.lock
  pkg/internal/test/test_doubles.go
  pkg/plugin/pr-sanitizer/event_handler.go
  pkg/plugin/pr-sanitizer/event_handler_gh_test.go
  pkg/plugin/test-keeper/event_handler.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/metrics_test.go
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/server/metrics_test.go
  pkg/server/server.go
Labels: size/L

#188 chore(#183): introduce functions for easy mocking GH requests in tests
  Gopkg.lock
  docs/fragments/test-suite.adoc
  docs/getting_started.adoc
  pkg/command/cmd_executor_test.go
  pkg/command/permission_service_test.go
  pkg/internal/test/mock_builder.go
  pkg/internal/test/mock_get_builder.go
  pkg/internal/test/mock_post_builder.go
  pkg/internal/test/payload_matchers.go
  pkg/internal/test/test_doubles.go
  pkg/plugin/pr-sanitizer/configuration_gh_test.go
  pkg/plugin/pr-sanitizer/event_handler_gh_test.go
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/custom_prefix_pr_edited.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/pr_details_wo_title_type.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/pr_edited_type_added.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/prs/pr_details.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/semantically_correct_pr_opened.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/semantically_correct_wip_pr_opened.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/semantically_incorrect_pr_opened.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/semantically_incorrect_wip_pr_opened.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/trigger_run_all_on_pr_by_admin.json
  pkg/plugin/pr-sanitizer/test_fixtures/github_calls/trigger_run_pr-sanitizer_on_pr_by_pr_creator.json
  pkg/plugin/test-keeper/configuration_gh_test.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/metrics_test.go
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/pr_details.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/run_cmd/trigger_run_all_comment_by_admin.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/run_cmd/trigger_run_test-keeper_comment_by_pr_reviewer.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/run_cmd/trigger_run_work-in-progress_comment_by_pr_reviewer.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/with_tests/status_edited.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/with_tests/status_opened.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/pr_details_for_metrics.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/skip_comment_by_admin.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/skip_comment_by_external.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/status_opened.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/status_opened_by_external_user.json
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/test-keeper-ignore-randomfile.yml
  pkg/plugin/test-keeper/test_keeper_status_service.go
  pkg/plugin/work-in-progress/configuration_gh_test.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/plugin/work-in-progress/test_fixtures/github_calls/custom_prefix_pr_opened.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_details.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_details_wip.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_edited_wip_added.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_edited_wip_removed.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_edited_with_label.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_edited_with_wip.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_labeled_wip.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/prs/pr_details.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/ready_pr_opened.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/trigger_run_all_on_wip_pr_by_admin.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/trigger_run_test-keeper_on_pr_by_pr_creator.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/trigger_run_work-in-progress_on_pr_by_pr_creator.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/wip_pr_created_with_label.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/wip_pr_opened.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/wip_pr_unlabeled.json
  pkg/server/metrics_test.go
  pkg/utils/url.go
Labels: size/XXL

#217 fix(#216): match more flavors around WIP prefixes
  docs/fragments/work-in-progress.adoc
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_unit_test.go
Labels: size/S
