Repository arquillian/ike-prow-plugins, pull requests merged in 2018-08, with the labels that each got.

#219 fix(#201): add status message to pr-sanitizer
  Gopkg.lock
  docs/fragments/pr-sanitizer.adoc
  docs/fragments/status/pr-sanitizer/failure/pr-sanitizer-failed.adoc
  docs/fragments/test-suite.adoc
  pkg/internal/test/mock_builder.go
  pkg/plugin/pr-sanitizer/checks.go
  pkg/plugin/pr-sanitizer/configuration.go
  pkg/plugin/pr-sanitizer/configuration_gh_test.go
  pkg/plugin/pr-sanitizer/event_handler.go
  pkg/plugin/pr-sanitizer/event_handler_gh_test.go
  pkg/plugin/pr-sanitizer/event_handler_unit_test.go
  pkg/plugin/pr-sanitizer/pr_sanitizer_message_builder.go
  pkg/plugin/pr-sanitizer/pr_sanitizer_status_service.go
  pkg/plugin/test-keeper/test_keeper_status_service.go
  pkg/status/message/message_loader.go
  pkg/status/message/message_service.go
Labels: size/XL

#223 fix(dep): fixes godep issue while resolving transitive fsnotify
  Gopkg.lock
  Gopkg.toml
  pkg/command/permission_types.go
  pkg/utils/secrets.go
Labels: size/L

#225 feat: add fabric8-cluster to the list
  cluster/osio-plugins.yaml
Labels: size/S
