Repository arquillian/ike-prow-plugins, pull requests merged in 2018-04, with the labels that each got.

#79 chore: renames null logger constructor
  pkg/github/comment_service_test.go
  pkg/github/status_service_test.go
  pkg/internal/test/test_doubles.go
  pkg/plugin/test-keeper/plugin/configuration_gh_test.go
  pkg/plugin/test-keeper/plugin/event_handler_gh_test.go
  pkg/plugin/work-in-progress/plugin/event_handler_gh_test.go
Labels: size/S

#74 feat: adds f8-jenkins-idler and f8-jenkins-proxy
  cluster/osio-plugins.yaml
Labels: size/S

#76 feat(#75): resends GH requests when response code is >= 404
  glide.lock
  pkg/github/client.go
  pkg/github/client_test.go
  pkg/github/comment_service.go
  pkg/github/comment_service_test.go
  pkg/github/config_loader.go
  pkg/github/status_service.go
  pkg/github/status_service_test.go
  pkg/http/retry.go
  pkg/http/url.go
  pkg/internal/test/test_doubles.go
  pkg/plugin/plugin_init.go
  pkg/plugin/pr-sanitizer/main.go
  pkg/plugin/test-keeper/main.go
  pkg/plugin/test-keeper/plugin/comment_message.go
  pkg/plugin/test-keeper/plugin/event_handler.go
  pkg/plugin/test-keeper/plugin/event_handler_gh_test.go
  pkg/plugin/work-in-progress/main.go
  pkg/plugin/work-in-progress/plugin/event_handler.go
  pkg/plugin/work-in-progress/plugin/event_handler_gh_test.go
  pkg/plugin/work-in-progress/plugin/event_handler_unit_test.go
  pkg/utils/retry.go
Labels: size/L

#81 fix: sets import path to the ike project specificaly
  .travis.yml
Labels: size/XS

#85 chore: refactoring of the comment_service
  pkg/github/comment_service.go
  pkg/github/hinter_service.go
  pkg/github/hinter_service_test.go
  pkg/plugin/test-keeper/plugin/event_handler.go
Labels: size/L

#86 fix(#87): retry function exits when response's exit code is < 404 and returns error that is not nil
  pkg/http/http_suite_test.go
  pkg/http/retry.go
  pkg/http/retry_test.go
  pkg/plugin/test-keeper/plugin/event_handler_gh_test.go
  pkg/utils/retry.go
Labels: size/L

#93 chore: updates prow hook service
  Makefile
  cluster/hook-template.yaml
  glide.lock
  glide.yaml
Labels: size/S

#94 fix(#92): excludes internal config files from test verification
  glide.lock
  pkg/assets/config/test-keeper.yaml
  pkg/config/config_loader_test.go
  pkg/config/test_fixtures/sample_configuration.yaml
  pkg/github/client.go
  pkg/github/config_loader.go
  pkg/http/retry.go
  pkg/http/retry_test.go
  pkg/internal/test/test_doubles.go
  pkg/plugin/plugin_init.go
  pkg/plugin/test-keeper/plugin/comment_message.go
  pkg/plugin/test-keeper/plugin/configuration.go
  pkg/plugin/test-keeper/plugin/event_handler.go
  pkg/plugin/test-keeper/plugin/event_handler_gh_test.go
  pkg/plugin/test-keeper/plugin/file_pattern.go
  pkg/plugin/test-keeper/plugin/file_pattern_test.go
  pkg/plugin/test-keeper/plugin/test_fixtures/github_calls/prs/without_tests/changes-with-test-keeper-config-excluding-other-file-from-PR.json
  pkg/plugin/test-keeper/plugin/test_fixtures/github_calls/prs/without_tests/test-keeper-ignore-randomfile.yml
  pkg/plugin/work-in-progress/plugin/event_handler.go
Labels: size/L

#82 feat: adds fabric8-launcher/launcher-backend
  cluster/osio-plugins.yaml
  test-keeper.yaml
Labels: size/XS

#103 feat: adds built-in assign plugin to this repo
  cluster/osio-plugins.yaml
Labels: size/XS

#89 feat(#73): bypassing test check is possible also for reviewers but not PR creator
  docs/fragments/test-keeper.adoc
  glide.lock
  glide.yaml
  pkg/command/cmd_executor.go
  pkg/command/cmd_executor_test.go
  pkg/command/cmd_handler.go
  pkg/command/cmd_handler_test.go
  pkg/command/cmd_suite_test.go
  pkg/command/permission_service.go
  pkg/command/permission_service_test.go
  pkg/github/client_test.go
  pkg/github/comment_service.go
  pkg/github/hinter_service.go
  pkg/github/pr_lazy_loader.go
  pkg/github/pr_lazy_loader_test.go
  pkg/github/repository_change.go
  pkg/internal/test/test_doubles.go
  pkg/plugin/test-keeper/plugin/comment_cmd.go
  pkg/plugin/test-keeper/plugin/comment_message.go
  pkg/plugin/test-keeper/plugin/comment_message_test.go
  pkg/plugin/test-keeper/plugin/event_handler.go
  pkg/plugin/test-keeper/plugin/event_handler_gh_test.go
  pkg/plugin/test-keeper/plugin/test_fixtures/github_calls/prs/without_tests/pr_details.json
  pkg/utils/strings.go
Labels: size/XXL

#102 feat(#71): check test file for additions/modifications to make PR green.
  pkg/github/client.go
  pkg/plugin/test-keeper/plugin/event_handler_gh_test.go
  pkg/plugin/test-keeper/plugin/file_categories.go
  pkg/plugin/test-keeper/plugin/test_fixtures/github_calls/prs/without_tests/deletions_only_changes_in_tests.json
  pkg/plugin/test-keeper/plugin/test_fixtures/github_calls/prs/without_tests/prod_code_changes_with_deletion_only_in_tests.json
  pkg/scm/types.go
Labels: size/L

#108 fix: rewords comments and disable deletion comment
  pkg/command/cmd_executor.go
  pkg/command/cmd_executor_test.go
  pkg/command/permission_service.go
  pkg/command/permission_service_test.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/utils/strings.go
Labels: size/M

#106 feat(#105): adds custom matcher for PermissionStatus and soft matcher for soft assertions
  glide.lock
  pkg/command/cmd_executor_test.go
  pkg/command/permission_service.go
  pkg/command/permission_service_test.go
  pkg/github/hinter_service_test.go
  pkg/github/status_service_test.go
  pkg/internal/test/gomega_matchers.go
  pkg/internal/test/payload_matchers.go
  pkg/internal/test/permission_status_matchers.go
  pkg/internal/test/soft_matcher.go
  pkg/internal/test/test_doubles.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
Labels: size/XL

#111 feat(#110): changes deployments to deploymentconfigs
  Makefile
  cluster/hook-template.yaml
  cluster/ike-prow-template.yaml
  test-keeper.yaml
Labels: size/M

#112 feat: adds more exclusion patterns
  pkg/assets/config/test-keeper.yaml
Labels: size/XS

#120 fix(#118): pr approver can also bypass test-keeper check
  pkg/command/permission_service.go
  pkg/command/permission_service_test.go
  pkg/github/client.go
  pkg/plugin/test-keeper/comment_cmd.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
Labels: size/M

#114 feat(#98): migrates images to use centos
  Dockerfile.builder
  Makefile
  cluster/hook-template.yaml
  cluster/ike-prow-template.yaml
  cluster/starter.yaml
  docs/getting_started.adoc
Labels: size/L

#121 chore(#95): expose hook version to openshift
  cluster/hook-template.yaml
Labels: size/XS

#126 fix(#124): unify repo name to be same as project name
  Makefile
Labels: size/XS

#84 feat(#41): adds support for inline comment for plugin_hint.
  docs/fragments/test-keeper.adoc
  docs/plugins.adoc
  pkg/config/config_loader.go
  pkg/github/config_loader.go
  pkg/plugin/test-keeper/comment_message.go
  pkg/plugin/test-keeper/comment_message_test.go
  pkg/plugin/test-keeper/configuration_gh_test.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/with_tests/test-keeper.yml
  plugins.yaml
Labels: size/L

#125 fix: corrects docker patterns and excludes .make directory
  Makefile
  pkg/assets/config/test-keeper.yaml
  pkg/plugin/test-keeper/matchers_test.go
Labels: size/M

#123 chore(#97): introduces CentosCi builds
  .make/Makefile.build
  .make/Makefile.deploy.prow
  .make/Makefile.docker.build
  .make/Makefile.openshift
  Dockerfile.builder
  Dockerfile.prow
  Makefile
  cico_run_tests.sh
  cico_setup.sh
  cluster/prow-baseline/branchprotector_cronjob.yaml
  cluster/prow-baseline/deck_deployment.yaml
  cluster/prow-baseline/deck_service.yaml
  cluster/prow-baseline/hook_deployment.yaml
  cluster/prow-baseline/hook_service.yaml
  cluster/prow-baseline/horologium_deployment.yaml
  cluster/prow-baseline/lego_deployment.yaml
  cluster/prow-baseline/mem-limit-range_limitrange.yaml
  cluster/prow-baseline/needs-rebase_deployment.yaml
  cluster/prow-baseline/needs-rebase_service.yaml
  cluster/prow-baseline/plank_deployment.yaml
  cluster/prow-baseline/prowjob_customresourcedefinition.yaml
  cluster/prow-baseline/pushgateway_deployment.yaml
  cluster/prow-baseline/sinker_deployment.yaml
  cluster/prow-baseline/splice_deployment.yaml
  cluster/prow-baseline/tide_deployment.yaml
  cluster/prow-baseline/tide_service.yaml
  cluster/prow-baseline/tls-ing_ingress.yaml
  cluster/prow-baseline/tot_deployment.yaml
  cluster/prow-baseline/tot_service.yaml
  glide.lock
  pkg/command/permission_service_test.go
  pkg/config/config_loader.go
  pkg/plugin/test-keeper/comment_message_test.go
  pkg/plugin/test-keeper/configuration_gh_test.go
  pkg/plugin/test-keeper/matchers_test.go
  setup.sh
Labels: size/XXL

#117 feat(#116): logs rate limits on any gh call
  glide.lock
  pkg/command/cmd_executor.go
  pkg/command/cmd_executor_test.go
  pkg/command/cmd_handler.go
  pkg/command/cmd_handler_test.go
  pkg/command/permission_funcs.go
  pkg/command/permission_service.go
  pkg/command/permission_service_test.go
  pkg/command/permission_types.go
  pkg/github/client.go
  pkg/github/client/client.go
  pkg/github/client/github_client_suite_test.go
  pkg/github/client/rate_limit_watcher_client.go
  pkg/github/client/rate_limit_watcher_client_test.go
  pkg/github/client/retry_client.go
  pkg/github/client/retry_client_test.go
  pkg/github/client/test_fixtures/gh/high_rate_limit.json
  pkg/github/client/test_fixtures/gh/low_rate_limit.json
  pkg/github/service/comment_service.go
  pkg/github/service/config_loader.go
  pkg/github/service/github_suite_test.go
  pkg/github/service/hinter_service.go
  pkg/github/service/hinter_service_test.go
  pkg/github/service/pr_lazy_loader.go
  pkg/github/service/pr_lazy_loader_test.go
  pkg/github/service/raw_file_service.go
  pkg/github/service/repository_change.go
  pkg/github/service/status_service.go
  pkg/github/service/status_service_test.go
  pkg/github/service/test_fixtures/github_calls/prs/comments_with_tests_keeper_message.json
  pkg/http/retry.go
  pkg/http/retry_test.go
  pkg/internal/test/test_doubles.go
  pkg/log/log.go
  pkg/plugin/plugin_init.go
  pkg/plugin/pr-sanitizer/cmd/main.go
  pkg/plugin/test-keeper/cmd/main.go
  pkg/plugin/test-keeper/comment_cmd.go
  pkg/plugin/test-keeper/comment_message.go
  pkg/plugin/test-keeper/comment_message_test.go
  pkg/plugin/test-keeper/configuration.go
  pkg/plugin/test-keeper/configuration_gh_test.go
  pkg/plugin/test-keeper/event_handler.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/file_categories_test.go
  pkg/plugin/test-keeper/test_status_service.go
  pkg/plugin/work-in-progress/cmd/main.go
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/plugin/work-in-progress/event_handler_unit_test.go
  pkg/retry/retry.go
  pkg/retry/retry_suite_test.go
  pkg/retry/retry_test.go
  pkg/utils/retry.go
  pkg/utils/url.go
Labels: size/XXL
