Repository arquillian/ike-prow-plugins, pull requests merged in 2018-05, with the labels that each got.

#128 feat(#62): adds health check probes to plugins.
  cluster/ike-prow-template.yaml
  pkg/plugin/plugin_init.go
  pkg/probes-handler/probes_handler.go
  pkg/probes-handler/probes_handler_suite_test.go
  pkg/probes-handler/probes_handler_test.go
Labels: size/L

#137 feat(#129): adds liveliness and readiness probes to the hook service.
  cluster/hook-template.yaml
Labels: size/XS

#132 chore(#97): adds centos-ci script that deploys images to devshift
  .make/Makefile.build
  .make/Makefile.deploy.prow
  .make/Makefile.docker.build
  Dockerfile.builder
  Makefile
  cico_build_deploy.sh
  cico_setup.sh
  cluster/hook-template.yaml
  cluster/ike-prow-template.yaml
  config/sentry-dsn
  glide.lock
  prow_version.sh
Labels: size/M

#146 Ignore codecov.io config file
  pkg/assets/config/test-keeper.yaml
Labels: size/XS

#136 fix(#135): removes unnecessary logging of GH API errors
  pkg/github/client/client.go
Labels: size/S

#149 chore(#150): adds RHEL based dockerfile used in CICO master build
  .make/Makefile.deploy.prow
  Dockerfile.deploy
  Dockerfile.deploy.rhel
  cico_run_tests.sh
  cico_setup.sh
Labels: size/M

#151 Rename config maps and secrets
  .make/Makefile.openshift
  cluster/hook-template.yaml
  cluster/ike-prow-template.yaml
Labels: size/M

#154 chore(#153): changes Sentry environment parameter to production
  pkg/plugin/plugin_init.go
Labels: size/XS

#152 Use IMAGE_TAG to comply with saasherder
  .make/Makefile.deploy.prow
  Makefile
  cico_setup.sh
  cluster/hook-template.yaml
  cluster/ike-prow-template.yaml
  prow_version.sh
Labels: size/M

#143 feat(#28): makes wip prefix configurable.
  docs/fragments/work-in-progress.adoc
  glide.lock
  pkg/plugin/work-in-progress/configuration.go
  pkg/plugin/work-in-progress/configuration_gh_test.go
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/plugin/work-in-progress/event_handler_unit_test.go
  pkg/plugin/work-in-progress/test_fixtures/github_calls/custom_prefix_pr_opened.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/work-in-progress.yml
Labels: size/XL

#161 fix(#160): wip plugin handles also synchronize PR action
  pkg/plugin/work-in-progress/event_handler.go
Labels: size/XS

#144 fix(#119): add new home for configuration files
  .ike-prow/test-keeper.yaml
  docs/fragments/test-keeper.adoc
  docs/fragments/work-in-progress.adoc
  docs/plugins.adoc
  glide.lock
  pkg/assets/config/test-keeper.yaml
  pkg/github/service/config_loader.go
  pkg/plugin/test-keeper/comment_message.go
  pkg/plugin/test-keeper/comment_message_test.go
  pkg/plugin/test-keeper/configuration_gh_test.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/with_tests/test-keeper.yml
  pkg/plugin/test-keeper/test_fixtures/github_calls/prs/without_tests/changes-with-test-keeper-config-excluding-other-file-from-PR.json
  pkg/plugin/work-in-progress/configuration_gh_test.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/utils/url.go
Labels: size/L

#164 chore(#163): upgrades to Go 1.10.2
  .travis.yml
  Dockerfile.builder
  README.adoc
  setup.sh
Labels: size/S

#162 fix(#165): base config always contains plugin name
  pkg/github/service/config_loader.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
Labels: size/S

#142 fix(#141): add service metrics for monitoring
  glide.lock
  pkg/github/client/client.go
  pkg/github/client/rate_limit_watcher_client.go
  pkg/github/client/retry_client.go
  pkg/plugin/plugin_init.go
  pkg/server/metrics.go
  pkg/server/metrics_test.go
  pkg/server/server.go
  pkg/server/server_suite_test.go
Labels: size/L

#168 fix(#166): uses gock networking only for POST requests
  pkg/server/metrics_test.go
Labels: size/S

#148 feat(#26): adds work-in-progress label.
  docs/fragments/work-in-progress.adoc
  pkg/github/client/client.go
  pkg/github/client/rate_limit_watcher_client.go
  pkg/github/client/retry_client.go
  pkg/internal/test/payload_matchers.go
  pkg/plugin/plugin_init.go
  pkg/plugin/work-in-progress/configuration.go
  pkg/plugin/work-in-progress/configuration_gh_test.go
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_edited_with_label.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/pr_edited_with_unlabel.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/wip_pr_created_with_label.json
  pkg/plugin/work-in-progress/test_fixtures/github_calls/work-in-progress.yml
Labels: size/XXL

#159 chore(#72): explains each plugin state in separated page
  .asciidoctor/generate.sh
  .asciidoctor/lib/const-inline-macro/extension.rb
  docs/fragments/status/test-keeper/failure/no-tests.adoc
  docs/fragments/status/test-keeper/success/keeper-approved-by.adoc
  docs/fragments/status/test-keeper/success/only-skipped.adoc
  docs/fragments/status/test-keeper/success/tests-exist.adoc
  docs/fragments/status/work-in-progress/failure/wip-failed.adoc
  docs/fragments/status/work-in-progress/success/wip-success.adoc
  docs/fragments/test-keeper.adoc
  docs/fragments/work-in-progress.adoc
  pkg/github/service/status_service.go
  pkg/github/service/status_service_test.go
  pkg/plugin/plugin_init.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/test-keeper/test_status_service.go
  pkg/plugin/work-in-progress/event_handler.go
  pkg/plugin/work-in-progress/event_handler_gh_test.go
  pkg/scm/status_service.go
Labels: size/L

#170 fix(#130,#158): merges client implementations and checks pagination
  glide.lock
  pkg/github/client/client.go
  pkg/github/client/pagination_checker.go
  pkg/github/client/pagination_checker_test.go
  pkg/github/client/rate_limit_watcher.go
  pkg/github/client/rate_limit_watcher_client.go
  pkg/github/client/rate_limit_watcher_test.go
  pkg/github/client/retry_client.go
  pkg/github/client/retry_wrapper.go
  pkg/github/client/retry_wrapper_test.go
  pkg/github/client/test_fixtures/gh/list_files_page_1.json
  pkg/github/client/test_fixtures/gh/list_files_page_2.json
  pkg/github/client/test_fixtures/gh/list_files_page_3.json
  pkg/internal/test/test_doubles.go
  pkg/log/log.go
  pkg/plugin/plugin_init.go
  pkg/plugin/test-keeper/event_handler.go
  pkg/plugin/test-keeper/event_handler_gh_test.go
  pkg/plugin/work-in-progress/event_handler.go
Labels: size/XL
